# HTTP Server.
server:
  address:             ":8199"
  dumpRouterMap:       true
  routeOverWrite:      true
  accessLogEnabled:    true
  openapiPath:         "/api.json"
  swaggerPath:         "/swagger"

# Global logging.
logger:
    level : "all"
    stdout: true

# Database.
database:
  logger:
    level:   "all"
    stdout:  true

  default:
    link:   "mysql:root:12345678@tcp(127.0.0.1:3306)/test"
    debug:  true

