# GoFrame CLI tool configuration.
gfcli:
  gen:
    dao:
      - link: "mysql:root:12345678@tcp(127.0.0.1:3306)/test"
        tables: "user"
        removePrefix: "gf_"
        descriptionTag: true
        noModelComment: true
